### ISSUE TITLE
NUT UPS stats not diplayed

### ISSUE THREAD

**Issue by mikegleasonjr** [norkator/apcupsd-monitor#107]
I successfully configure a NUT UPS, it seems to connect but no Infos are reported. When I click 'debug informations' I see the payload returned. But it looks like the text encoding maybe isn't right, maybe that's the problem. The host is TrueNAS Scale with the UPS plugin. Other clients can fetch data property from the server:

```
BEGIN LIST VAR eatonbattery.charge "11"battery.charge.low "35"battery.runtime "215"battery.type "PbAc"device.mfr "EATON"device.model "Ellipse ECO 650"device.serial "000000000"device.type "ups"driver.name "usbhid-ups"driver.parameter.pollfreq "30"driver.parameter.pollinterval "2"driver.parameter.port "/dev/uhid"driver.parameter.synchronous "no"driver.version "2.7.4"driver.version.data "MGE HID 1.40"driver.version.internal "0.41"input.transfer.high "264"input.transfer.low "184"outlet.1.desc "PowerShare Outlet 1"outlet.1.id "2"outlet.1.status "on"outlet.1.switchable "no"outlet.2.desc "PowerShare Outlet 2"outlet.2.id "3"outlet.2.status "on"outlet.2.switchable "no"outlet.desc "Main Outlet"outlet.id "1"outlet.power "25"outlet.switchable "no"output.frequency.nominal "50"output.voltage "230.0"output.voltage.nominal "230"ups.beeper.status "enabled"ups.delay.shutdown "20"ups.delay.start "30"ups.firmware "02"ups.load "8"ups.mfr "EATON"ups.model "Ellipse ECO 650"ups.power.nominal "650"ups.productid "ffff"ups.serial "000000000"ups.status "OL"ups.timer.shutdown "0"ups.timer.start "0"ups.vendorid "0463"END LIST VAR eaton
```

**Comment by norkator** [comment]
![Screenshot 2022-03-19 at 12 43 14](https://user-images.githubusercontent.com/55850510/159117839-9fbcfa06-7eff-4795-9348-c8dff3e08e58.png)

This is related to my current NUT implementation being half baked.

Current StatusParser made by other user expects NUT lines being in format like `ups.status: OL` but here it comes like `ups.status "OL"`. I tweaked this a bit how lines are saved before Parser because I don't want to modify Parser itself.

I will push update on this. Not perfect yet but lets see what happens.

**Comment by mikegleasonjr** [comment]
Amazing thanks 👍

**Comment by norkator** [comment]
> Amazing thanks 👍

Update should be available. Can you report later does it actually work with your NUT host.

**Comment by mikegleasonjr** [comment]
![Screenshot_20220319-145420_APCUPSD Monitor](https://user-images.githubusercontent.com/1644534/159123992-7e3f350b-158d-4673-9d4c-e0bbcbc33987.png)

S
![Screenshot_20220319-145411_APCUPSD Monitor](https://user-images.githubusercontent.com/1644534/159123994-07024581-4ba5-4dba-b231-88df284af968.png)


Seems to work thanks 👍😊
