### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by XSvirusSAFE** [norkator/apcupsd-monitor#127]
Every time i add a nut server the app crashes and wont open. After cleaning the cahes i am able to access the app again.

**Comment by XSvirusSAFE** [comment]
And app data.

**Comment by norkator** [comment]
@XSvirusSAFE did you give NUT server address in fully qualified domain name format like `name@192.168.1.1` ?

**Comment by XSvirusSAFE** [comment]
All is good now, I saw my mistake.
