### ISSUE TITLE
Feature request: configure displayed items on main screen

### ISSUE THREAD

**Issue by bo0tzz** [norkator/apcupsd-monitor#29]
There's currently an option to configure the items that are displayed in the detail screen. I'd also like an option to configure the items that are shown on the main screen, so that I can get a quick overview of the values I care about across all my UPSes.

**Comment by norkator** [comment]
I have no other idea than adding another set of settings but for front page at settings to toggle what user wants to see. Maybe have some few obvious ones but no like firmware version as example?

**Comment by bo0tzz** [comment]
>What about the overall view available space? stack items like now but what ever how many items are selected.

I'm not sure what you mean by this?
>another set of settings but for front page at settings to toggle what user wants to see

That's basically what I'm thinking, yeah. Indeed fairly static things like firmware version wouldn't be necessary. Personally I'd use it to view things like remaining runtime.

**Comment by norkator** [comment]
> > What about the overall view available space? stack items like now but what ever how many items are selected.
> 
> I'm not sure what you mean by this?
> 
> > another set of settings but for front page at settings to toggle what user wants to see
> 
> That's basically what I'm thinking, yeah. Indeed fairly static things like firmware version wouldn't be necessary. Personally I'd use it to view things like remaining runtime.

"option to configure the items that are shown on the main screen"
I meant that after fifth line view comes bloated and its going over battery charge percentage gauge making it uglier, that doesn't matter?

**Comment by bo0tzz** [comment]
Oh, yeah that makes sense. I guess you could limit it to a certain number of enabled items if it mattered?

**Comment by norkator** [comment]
@bo0tzz can you do code review +if you have ideas to do things better way, please comment about them.

**Comment by bo0tzz** [comment]
Sure, I'll give it a review later today
