### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by 7thCore** [norkator/apcupsd-monitor#7]
Would it be possible to implement push notifications when the app detects a UPS is on power or went offline?

Possible notification/alert options:
-on battery
-offline
-online
-battery change
-low battery
-UPS issue shutdown

**Comment by norkator** [comment]
Answer is yes. Something like Google Firebase could handle triggering of status check, but not too often so that phone battery is not eaten alive. There currently is notification implementation but it may not work on all devices.

**Comment by 7thCore** [comment]
You could make the interval a user setting in minutes for the user to configure what he/she is comfortable with

**Comment by norkator** [comment]
@7thCore I need to know exact strings how your UPS is returning statuses what you mentioned:
-on battery
-offline
-online
-battery change
-low battery
-UPS issue shutdown

but I need exact details (open ups at app and right corner "debug output" should help to get these details)
