### ISSUE TITLE
Ability to disable ups momentarily

### ISSUE THREAD

**Issue by norkator** [norkator/apcupsd-monitor#70]
Need this because removed one ups for maintenance but its blocking update.

**Comment by bo0tzz** [comment]
How is it blocking update? Maybe instead make a change so UPSes update independently?

**Comment by norkator** [comment]
> How is it blocking update? Maybe instead make a change so UPSes update independently?

Yeah should implement them to update independently as a one thing. I just want to skip one ups completely and mark it as disabled with gray coloring at UI.
