### ISSUE TITLE
2 x Features requests for apcupsd-monitor

### ISSUE THREAD

**Issue by sonicprod** [norkator/apcupsd-monitor#98]
In APCUPSD mode:

1. Please add support for upsd "instance": we specify it with a @ on front of the FQDN for monitoring the correct upsd master host instance (as defined in ups.conf). For example: usbhid@ex4100.localdomain refer to the instance "usbhid" from ex4100.localdomain master upsd host. Please refer to section "6.2. Basic configuration", subsection "Driver configuration" at https://networkupstools.org/docs/user-manual.chunked/ar01s06.html
 
2. Please add support for authenticated upsd requests by username and password (as defined in the file upsd.users on the master upsd host). For more details, please refer to: https://networkupstools.org/docs/man/upsd.users.html

**Comment by norkator** [comment]
@sonicprod I personally have not used NUT so have to ask that:
1. I just basically download it from https://networkupstools.org/download.html and can use it with APC or Eaton UPSes right?
2. I wonder can I set this up without having physical UPS at all. Do you know?

**Comment by sonicprod** [comment]
Hi,

1. Yes, you are correct.

2. You can use the dummy-ups driver to simulate a real UPS. Please see: https://www.systutorials.com/docs/linux/man/8-dummy-ups/

**Comment by norkator** [comment]
Do you use SSH? I started implementing this using port 3493 with socket connection but it might not be what you want?

**Comment by norkator** [comment]
I am asking this because https://networkupstools.org/docs/developer-guide.chunked/ar01s09.html looks to give me possibility to do all sorts of stuff:

![Screenshot 2022-01-22 at 18 14 59](https://user-images.githubusercontent.com/55850510/150646682-ae897ce4-6521-4229-b50f-aad04bb5fd8e.png)

**Comment by norkator** [comment]
username and password setup wont work no matter what I do. It's unclear how to set it up right.
